### PR TITLE
fixed CalDav on calendar mode

### LINKED ISSUE #392: No icons (or event text of any kind) in Calendar mode using caldav integration
I'm using the caldav integration pointing to a Nextcloud instance which works in HA's calendar, shows all four of the calendars I've defined, and works in the Event view.

## Expected behaviour
I would expect to see icons on days where events exist in the Calendar mode.

## Current behaviour
I do not see any indication of any events in the Calendar mode.

## Screenshot
Screenshot from 2021-01-25 11-19-18
On the left is the HA calendar card for reference. As you can see, events are indicated here, but not on the atomic-calendar-revive card.

## Possible reasons and solutions
As noted [here](https://marksie1988.github.io/atomic-calendar-revive/quickstart.html#more-than-5) even with the google-calendar integration, extra configuration is required to show more than 5 events. The configuration options for google calendar and caldav are different, so it's possible that atomic calendar revive is looking for a parameter that is missing from the caldav integration. This is speculation, of course. :)

## Steps to reproduce
Add a caldav calendar in configuration.yaml like this:

```
calendar:
  - platform: caldav
    days: 45
    username: !secret nc_user
    password: !secret nc_pw
    url: !secret nc_url
```

With this configuration, available calendars are detected and added automatically. If the developers do not have access to a working caldav calendar, I would be happy to create a dummy calendar and temporary credentials on my server to facilitate resolving this issue. 

## Your environment
Running a Supervised instance of the latest HA 2021.1.5 on x86 hardware on Ubuntu 18.04 LTS. I have been running the same instance for about a year, upgrade regularly and have significant experience as a Linux system administrator and software engineer. I run a tight ship and RTFM regularly. :)

## Checklist
- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [ ] I am mostly sure that the problem is related to the code and isn't my fault.

Please let me know what else I can do to help get this sorted - I love the card and would love to use it to help my family plan their day!

### PR DESCRIPTION
**Pull request by marksie1988**
## Description

CalDav was not showing any events in Calendar mode, Code has been re-worked for Calendar mode to be more efficient and also to show CalDav as expected along with Google Calendar

## Related issues

- fixes #392 

## Motivation and Context

Calendar mode doesn't show events for CalDav connections

## How has this been tested

Tested on my dev instance

## Types of changes

- [ ] Docs change / refactoring.
- [x] Non-breaking change (fix or feature that wouldn't cause existing functionality to change/break).
- [ ] Breaking change (fix or feature that would cause existing functionality to change/break).

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes don't generate new warnings.
- [x] I have read the [CONTRIBUTING](https://github.com/marksie1988/.github/blob/master/docs/CONTRIBUTING.md) document.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by Olen** [comment]
I have the same problem with our ical custom_component.  Is there an issue with the calendar format?
I don't really see what this PR fixes, but it seems to be something realted to whether there is an event.start.dateTime or an event.start.date or something.
W can modify the ical integraton to match what google does if that has changed lately.

**Comment by marksie1988** [comment]
Hey @Olen, 

Home Assistant handles both Google and CalDav differently which is a real pain, the dates are stored in different locations and as you have shown above. 

I have had to add checks to see how the date is presented which will then decide how to set the date.

**Comment by Olen** [comment]
Hi, and thanks.  We based the ical-calendar on the caldav-integration, and it used to work in atomic-revive until some update a little hile ago.  But I can change the ical integration to whatever you think is best. Just need to know how you would prefer it.

```
        self._event["start"]["dateTime"] = event["start"].isoformat()
        self._event["end"]["dateTime"] = event["end"].isoformat()
        self._offset_reached = is_offset_reached(self.event)
        self._event["all_day"] = event["all_day"]
```
Are there any other attributes we should use to match either google or caldav? 
It works fine in event mode, but not in calendar mode...

**Comment by marksie1988** [comment]
so google calendar will use start.date for full day or start.datetime for a normal event, which would make it easier if both the same

**Comment by Olen** [comment]
Sorry I keep on posting in the closed PR, I am just uncertain if I should open another issue request here, or if I should fix the ical implemetation...
I must admit the code in "getCalendarEvents" is currently beyond my comprehension...
I added some debugging to the card, and the events from ical calendars came up as the atached image.

I can see that the format in "f" and "i" does not match, as the date ical provides adds the UTC-offset (+0100), but I don't know if that is the root cause?

Screenshot from 2021-01-31 15-16-12

**Comment by Olen** [comment]
Now, this is weird!
When I added a single line with "console.log" to get the debug output above, the events from ical is starting to show up...

(Well, what I did was to use an online de-minifier on the provided atomic-calendar-revive.js from hacs.  The add a debug line, and replace the file in the `/www/community/atomic-calendar-revive` folder.  And do a full reload and refresh...

It could have been a caching problem or something.

**Comment by marksie1988** [comment]
Quite possibly, if this is still an issue please open a new issue to properly discuss. 

I think that if you have issues with your sensor and it matches the same format as caldav then it should work without issue, if it is having issues I'm more than happy to look but would obviously need to setup the sensor which I don't currently use.

**Comment by Olen** [comment]
I really think the calendar format should be explicitly defined so all implementations can do it the same way.
But thank you for your patience.

**Comment by marksie1988** [comment]
I totally agree, it's a bit of a bad choice on HAs implementation there. I guess a feature change request they may implement it.

**Pull request merged**
